version: '3'
services:
  db:
    build: ./db
    env_file: .env  
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "milsapcory@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "5050:80"
    depends_on:
      - db

  cron-jobs:
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./cron-jobs/Dockerfile

  server:
    env_file: .env
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app 
      - ./db:/app/db

  newsai-frontend:
    build: ./NewsAI
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"

volumes:
  postgres_data: