version: '3'
services:
  db:
    build: ./db
    env_file: .env  
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  cron_jobs:
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./cron_jobs/Dockerfile