version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  cron_jobs:
    image: cron_jobs
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_PASSWORD: postgres
